### ISSUE TITLE
API Doesn't Work For Uploading Attachments (PDFs)

### ISSUE THREAD

**Issue by JonasMS** [tnajdek/zotero-api-client#10]
I have the following code:
```
const createdItemRes = await zoteroLibrary
.items()
.post([newItem]),

createdItem = createdItemRes.getData()[0];

const attachmentRes = await zoteroLibrary
.items(createdItem.key)
.attachment(documentData.title, pdfArrayBuffer)
.post();
```

This results in the following response error: `Error: Upload stage 1: File already exists.`

If, on the other hand, I do
```
const attachmentRes = await zoteroLibrary
                    .items()
                    .attachment(documentData.title, pdfArrayBuffer)
                    .post([newItem]);
```

I get the following runtime error: `Cannot use both "file" and "body" in a single request.`

**Comment by tnajdek** [comment]
An attachment in Zotero is actually an item with `itemType` set to 'attachment', it also should have ` 'linkMode` property, please see [documentation](https://www.zotero.org/support/dev/web_api/v3/file_upload) for more details. Attachments can exist on their own (as top level/standalone items) but usually are attached to other items. For the purpose of this example, we will attach the attachment item to another item identified by key **SOMEITEM**.

Here is a complete example how to create an item and upload a file (image) using `zotero-api-client`:

Let's say we have:
````js
var api = require('zotero-api-client');
var fs = require('fs');
var filedata = fs.readFileSync('picture.jpg');
````

And some configuration:

````js
const APIKEY = 'YOURAPIKEYHERE';
const USERID = 'YOURUSERIDHERE';
const ITEM_KEY = 'SOMEITEM'; // this is going to be the parent item
````

First we need to obtain the item template:

````js
const template = (await api()
	.template('attachment')
	.get({ linkMode: 'imported_file'})).getData();
````

Then build the attachment item object:

````js
const item = {
	...template,
	title: 'attached picture',
	parentItem: ITEM_KEY,
	filename: 'picture.jpg',
	contentType: 'image/jpeg',
};
````

Then create it:

````js
const attachmentItem = (await api(APIKEY)
	.library(USERID)
	.items()
	.post([item])).getEntityByIndex(0);
````

Finally we upload a file and associate it with newly created attachment item:

````js
const response = await api(APIKEY)
	.library(USERID)
	.items(attachmentItem.key)
	.attachment('picture.jpg', filedata.buffer)
	.post();
````


You can download the complete example [here](https://gist.github.com/tnajdek/4ad304b1b9ba0bc3b51cdfc136f7f66a). Hope this helps!

**Comment by tnajdek** [comment]
When the attachment item is deleted from Zotero, the attachment file itself will not be purged for some time, could it be that you're trying to re-upload file that you have previously uploaded? In that case the API will still create file association with the existing file so it should still work despite the error. Could you please confirm if this actually worked (for example by using the client to see if the attachment item is created)?

Perhaps the problem here is that `zotero-api-client` incorrectly reports this situation as an error when it actually isn't one.

**Comment by JonasMS** [comment]
Ahah! You are correct, the PDF was correctly uploaded.

🙏Huge help, thank you!

Indeed, perhaps in this case the file upload should be considered successful and it's status of already existing being noted in the success response.

**Comment by tnajdek** [comment]
@JonasMS Begining with version 0.22.0, `zotero-api-client` will no longer consider "File Already Exists" response as an error. I believe that's a better behaviour and will help avoid confusion like that in the future.

It's still possible to check whether existing file was used by looking at `response.getData().exists` where `response` is an instance of `FileUploadResponse`.
