### ISSUE TITLE
missing dependency item in package.json 

### ISSUE THREAD

**Issue by boan-anbo** [tnajdek/zotero-api-client#16]
`Error: Cannot find module 'regenerator-runtime/runtime'`

Need to manually install the regenerator runtime.

**Comment by AJamesPhillips** [comment]
I can confirm I am getting this error too and it is fixed by: `npm install regenerator-runtime`, so perhaps `regenerator-runtime` should be added to the dependencies list?  It seems though this is coming from babel so perhaps it's a bug they have now fixed?

**Comment by tnajdek** [comment]
Thank you both for reporting. For legacy reasons I've been processing src files prior to packaging but this is no longer needed, hasn't been for years. Will be fixed in the next release.

**Comment by AJamesPhillips** [comment]
Thank you very much @tnajdek ! 😀
