### ISSUE TITLE
Add support for Observable

### ISSUE THREAD

**Issue by buccalon** [tnajdek/zotero-api-client#18]
Hi Tom, thanks for your work on this client.

I'd like to use it within [Observable](https://observablehq.com/@observablehq/module-require-debugger), but their `require` is giving me some pain.

According to their module debugger, the issue is related to the module's entry point:

![image](https://user-images.githubusercontent.com/476699/109404607-7dca1780-7946-11eb-86f9-6bbfbfb6f6ca.png)

I don't know how much effort this would take, but I'd appreciate your attention.

Cheers, Bruno.

**Comment by tnajdek** [comment]
I've introduced some hints as the where UMD bundle can be found in `package.json` and now we get three 👍 on the page you've linked which I hope is sufficient for it to work?

I've also documented the fact that UMD bundle is indeed part of the NPM package as it wasn't mentioned in the README before.

Hope this works, please feel free to re-open the issue in case it didn't resolve the problem.
