### ISSUE TITLE
Replacing an attachment 

### ISSUE THREAD

**Issue by cboulanger** [tnajdek/zotero-api-client#19]
The [zotero attachment upload API](https://www.zotero.org/support/dev/web_api/v3/file_upload) is quite complex, to say the least, but your API client makes it much more manageable, even though it still isn't trivial. Using your [example code](https://gist.github.com/tnajdek/4ad304b1b9ba0bc3b51cdfc136f7f66a), I was able to  upload new attachments.  Could you also give an example how to replace an existing one? I wasn't quite sure how to use `registerAttachment()` in this scenario.

Thank you very much for you library, it makes my work so much easier!

**Comment by tnajdek** [comment]
`registerAttachment` is for a scenario where you need to associate an already-uploaded attachment file Zotero knows about with a new attachment item so maybe not what you're looking for?

I've just pushed a new version `0.36.0` where `attachment()` now takes the fourth argument which is an md5 hashsum of an existing item. With this version you can now upload a new file for given attachment item, here is the same [example code extended to override the existing file](https://gist.github.com/tnajdek/b2392ee558314aa0d559475b3ff3cf71).

**Comment by cboulanger** [comment]
Cool, thank you so much for the quick response and the update! Much appreciated.
