### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by HughP** [tnajdek/zotero-api-client#20]
Greetings,

This project looks interesting. Before I start playing around with it in my project, what is the license? I'm pretty restricted to MIT/BSD, so I just want to make sure I'm not pulling in an AGPL package.

**Comment by tnajdek** [comment]
Hi,

The license is AGPL-3.0 as stated as in package.json. I've added a COPYING file to make it more clearly stated. Sorry it doesn't meet your requirements.

Cheers!
Tom
