### ISSUE TITLE
Feature request: Support 'verify key access' and  'get updated group metadata' request

### ISSUE THREAD

**Issue by cboulanger** [tnajdek/zotero-api-client#21]
I am using the library to make a local copy of my personal and group libraries on zotero.org. As far as I can see, the "verify key access" (https://www.zotero.org/support/dev/web_api/v3/syncing#verify_key_access) request is not yet supported. Is there a workaround so this can be done using the API, otherwise I use a manually configured `fetch`. However, it would be great if this request type would be built in. 

Thank you.

**Comment by cboulanger** [comment]
This also applies to the "Get updated group metadata" request (https://www.zotero.org/support/dev/web_api/v3/syncing#get_updated_group_metadata).

Of course, getting it is a matter of a simple 

```javascript
await (await fetch(`https://api.zotero.org/users/${userId}/groups?format=versions`, {
        headers: {"Zotero-API-Key": this.__api_key}
      })).json();
```
but maybe you also think that it might be good to include it into the library.

**Comment by tnajdek** [comment]
The latter is already possible:
```` javascript
        const response = await api()
			.library('user', USER_ID)
			.groups()
			.get({ format: 'versions' });
		
        const data = await response.getData().json();
````

Or in standard format with all the details about the group:
````javascript
        const response = await api()
			.library('user', USER_ID)
			.groups()
			.get();
		
        const data = response.getData();
````

I agree key verification would be nice to have. I'm quite busy at the moment but I'll look into it eventually.
