### ISSUE TITLE
Reopening:  Incorrect URL is generated for template requests

### ISSUE THREAD

**Issue by natejlong** [tnajdek/zotero-api-client#24]
Originally opened at https://github.com/tnajdek/zotero-api-client/issues/9 . Here's the original author's description of the problem:

> Using the below code:
> 
> ```
> const newItem = await zotero(userEntity.zotero_api_key)
>                         .library('user', userEntity.zotero_user_id)
>                         .template('journalArticle')
>                         .get();
> ```
> 
> Expected: Fetch a new item template.
> 
> Actual: 404 Error. This operation is calling `https://api.zotero.org/users/[USER_ID]/items/new?format=json&itemType=journalArticle`
> 
> According to the Zotero API docs ([link](https://www.zotero.org/support/dev/web_api/v3/types_and_fields#getting_a_template_for_a_new_item)) the following path should be used: `/items/new?itemType=journalArticle`.

The author quickly closed the issue a few minutes after creating it, but I just ran into this myself and it seems like the issue is still present.

I looked into it a tiny bit and the resource in request.js will need to be special-cased so that it uses a new root path instead of appending to the users path. Not sure what the cleanest way to do this is though https://github.com/tnajdek/zotero-api-client/blob/d0494145e0e60eca32c59880d89735b570b9db11/src/request.js#L73 

You can confirm the problem via checking out the urls manually:

- https://api.zotero.org/users/[INSERT AN ID]/items/new?format=json&itemType=journalArticle

- https://api.zotero.org/items/new?format=json&itemType=journalArticle

Thanks for the client library too! Very useful

**Comment by tnajdek** [comment]
Templates are not library-specific, thus you should not specify library. Corrected usage, based on your example would be:
````js
const newItem = await zotero(userEntity.zotero_api_key)
                        .template('journalArticle')
                        .get();
````
At some point in the future I'm planning to add checks for requests like this (#2).

**Comment by natejlong** [comment]
Ahh I see, thanks a ton for the quick solution!
