### ISSUE TITLE
Question: What is the best way to request next page in paginated response?

### ISSUE THREAD

**Issue by papr** [tnajdek/zotero-api-client#25]
If one requests an API call with a paginated response, what is the best way to get the results of the next page using this JS client?

The web api [specifies links in the response headers, pointing to the last/next pages](https://www.zotero.org/support/dev/web_api/v3/basics#sorting_and_pagination). Does this JS client have a built-in option to fetch these as well?

**Comment by tnajdek** [comment]
There is no API for parsing headers yet but I can see how this would be useful, so I'll add something soon.

That being said, every response from the API contains a key named `response` which is an instance of [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) from fetch. This means that `response.response.headers` is where next/last pages can be found but it will require parsing. Here is a complete example ([run on jsfiddle](https://jsfiddle.net/v5hygbwf/)):

````js
const { default: api } = ZoteroApiClient;

const getNextLinkFromResponse = response => {
  let next = null;
  if(response.headers.has('link')) {
    const links = response.headers.get('link');
    const matches = links.match(/<(.*?)>;\s+rel="next"/i);

    if(matches && matches.length > 1) {
      next = matches[1];
    }
  }
  return next;
}

(async () => {
  let response = await api()
    .library('u475425')
    .top()
    .items()
    .get();

  console.log(getNextLinkFromResponse(response.response));
})();

````

In practice however, you will most likely want to maintain pagination yourself. Get total results from the first response (`response.response.headers.get('total-results')`) and use `start` and `limit` parameters for pagination.

**Comment by papr** [comment]
@tnajdek Thank you for your thorough response! I have implemented the manual pagination approach successfully.

10/10 support 👌🏻
