### ISSUE TITLE
zotero-lib

### ISSUE THREAD

**Issue by bjohas** [tnajdek/zotero-api-client#31]
Hello all,

Just wondering whether you're aware of our zotero-lib (nodejs) api wrapper:
https://github.com/OpenDevEd/zotero-lib

Would you want to discuss to see how we could collaborate?

Many thanks!

**Comment by tnajdek** [comment]
If you have any suggestions for this library, please let me know - feel free to open new issues for feature suggestions. That being said, please bear in mind that the idea is to keep this library small and simple as explained in the README.
