### ISSUE TITLE
Feature request: API url from response (was: Question: Is it possible to get the API url from the response?)

### ISSUE THREAD

**Issue by bjohas** [tnajdek/zotero-api-client#6]
I noticed that it's part of the error message, but can't see how to get it if the query is successful.

**Comment by tnajdek** [comment]
Currently it's not stored anywhere so the answer is no. The closest you can get from the api is `response.options` which includes configuration used to make the request.

**Comment by bjohas** [comment]
Many thanks! I'd like to put this forward as a feature request then!

**Comment by tnajdek** [comment]
The entire [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) object is stored on the API Response object as `response` and that contains the actual url requested.

So assuming you're running example from the README:

        const response = await api().library('user', 475425).collections('9KH9TNSJ').items().get();

You can get the url requested:

        console.log(response.response.url)
